from django.db import models

class Task(models.Model):
  title = models.CharField(max_length=200)
  completed = models.BooleanField(default=False, blank=True, null=True)

  def __str__(self):
    return self.title

class entail_py(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_ld(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet

class entail_wb(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet

class entail_or(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet



class entail_br(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_sk(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_ct(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_tn(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_mp(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_gj(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_ga(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_nl(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_mn(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_ar(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_mz(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_tr(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_dd(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_dl(models.Model):
  # tweet_id = models.BigIntegerField(default=0)
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()

  def __str__(self):
    return self.tweet


class entail_hr(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_ch(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_hp(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_jk(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_kl(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet

class entail_ka(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_dn(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_mh(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_as(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_ap(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_ml(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_pb(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_rj(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_up(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet


class entail_ut(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet



class entail_jh(models.Model):
  tweet = models.CharField(max_length=500)
  res_cls = models.CharField(max_length=10)
  prob_cls = models.FloatField()
  res_ent = models.CharField(max_length=10)
  prob_ent = models.FloatField()
  iids = models.CharField(max_length=100)
  u1 = models.CharField(max_length=300)
  u1res = models.CharField(max_length=10)
  u1prob = models.FloatField()
  u2 = models.CharField(max_length=300)
  u2res = models.CharField(max_length=10)
  u2prob = models.FloatField()
  u3 = models.CharField(max_length=300)
  u3res = models.CharField(max_length=10)
  u3prob = models.FloatField()
  u4 = models.CharField(max_length=300)
  u4res = models.CharField(max_length=10)
  u4prob = models.FloatField()
  u5 = models.CharField(max_length=300)
  u5res = models.CharField(max_length=10)
  u5prob = models.FloatField()
  u6 = models.CharField(max_length=300)
  u6res = models.CharField(max_length=10)
  u6prob = models.FloatField()
  u7 = models.CharField(max_length=300)
  u7res = models.CharField(max_length=10)
  u7prob = models.FloatField()
  u8 = models.CharField(max_length=300)
  u8res = models.CharField(max_length=10)
  u8prob = models.FloatField()
  u9 = models.CharField(max_length=300)
  u9res = models.CharField(max_length=10)
  u9prob = models.FloatField()
  u10 = models.CharField(max_length=300)
  u10res = models.CharField(max_length=10)
  u10prob = models.FloatField()
  def __str__(self):
    return self.tweet
