# Generated by Django 3.0.3 on 2020-07-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entail_dli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=500)),
                ('FNF', models.CharField(max_length=10)),
                ('prob', models.FloatField()),
                ('iids', models.CharField(max_length=100)),
                ('u1', models.CharField(max_length=300)),
                ('u2', models.CharField(max_length=300)),
                ('u3', models.CharField(max_length=300)),
                ('u4', models.CharField(max_length=300)),
                ('u5', models.CharField(max_length=300)),
                ('u6', models.CharField(max_length=300)),
                ('u7', models.CharField(max_length=300)),
                ('u8', models.CharField(max_length=300)),
                ('u9', models.CharField(max_length=300)),
                ('u10', models.CharField(max_length=300)),
            ],
        ),
    ]
